# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mydiscretizeMDL <- function(RmyDist, RmaxBins) {
    .Call('_miic_mydiscretizeMDL', PACKAGE = 'miic', RmyDist, RmaxBins)
}

mydiscretizeMutual <- function(input_data, arg_list) {
    .Call('_miic_mydiscretizeMutual', PACKAGE = 'miic', input_data, arg_list)
}

reconstruct <- function(input_data, arg_list) {
    .Call('_miic_reconstruct', PACKAGE = 'miic', input_data, arg_list)
}

