# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

evaluateEffn <- function(inputDataR, variable_numR, sample_numR) {
    .Call('_miic_evaluateEffn', PACKAGE = 'miic', inputDataR, variable_numR, sample_numR)
}

mydiscretizeMDL <- function(RmyDist, RmaxBins) {
    .Call('_miic_mydiscretizeMDL', PACKAGE = 'miic', RmyDist, RmaxBins)
}

mydiscretizeMutual <- function(RmyDist1, RmyDist2, RflatU, RnbrU, RmaxBins, Rinitbin, Rcplx, Rcnt_vec, Rnlevels, ReffN, RsampleWeights) {
    .Call('_miic_mydiscretizeMutual', PACKAGE = 'miic', RmyDist1, RmyDist2, RflatU, RnbrU, RmaxBins, Rinitbin, Rcplx, Rcnt_vec, Rnlevels, ReffN, RsampleWeights)
}

reconstruct <- function(inputDataR, cntVarR, numNodesR, nThreadsR, edgefileR, blackBoxR, effNR, cplxR, etaR, hvsR, isLatentR, isTplReuseR, isK23R, isDegeneracyR, orientationR, propagationR, isNoInitEtaR, confidenceShuffleR, confidenceThresholdR, sampleWeightsR, consistentR, testDistR, verboseR) {
    .Call('_miic_reconstruct', PACKAGE = 'miic', inputDataR, cntVarR, numNodesR, nThreadsR, edgefileR, blackBoxR, effNR, cplxR, etaR, hvsR, isLatentR, isTplReuseR, isK23R, isDegeneracyR, orientationR, propagationR, isNoInitEtaR, confidenceShuffleR, confidenceThresholdR, sampleWeightsR, consistentR, testDistR, verboseR)
}

